<Project Sdk="Microsoft.NET.Sdk.Web">
<PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
  <Nullable>disable</Nullable>
  <ImplicitUsings>enable</ImplicitUsings>
</PropertyGroup>

<!-- Build React before ASP.NET -->
<Target Name="BuildReact" BeforeTargets="Build">
    <Exec Command="npm install" WorkingDirectory="$(MSBuildProjectDirectory)\ClientApp" />
    <Exec Command="npm run build" WorkingDirectory="$(MSBuildProjectDirectory)\ClientApp" />
</Target>

  <ItemGroup>
    <Using Include="EPiServer" />
    <Using Include="EPiServer.Core" />
    <Using Include="EPiServer.DataAbstraction" />
    <Using Include="EPiServer.DataAnnotations" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.17.1" />
    <PackageReference Include="EPiServer.CMS" Version="12.34.2" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.2" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.15.0" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
    <PackageReference Include="Optimizely.ContentGraph.Cms" Version="4.3.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.12" />
    <PackageReference Include="Wangkanai.Detection" Version="8.7.0" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Remove="src\**\*.ts" />
    <Compile Remove="src\**\*.tsx" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="ClientApp\src\queries\" />
  </ItemGroup>
</Project>
