query GetContentItems($first: Int, $after: String, $locale: [Locales!]) {
  content(first: $first, after: $after, locale: $locale) {
    edges {
      node {
        id
        displayName
        changed
        published
        ... on Page {
          heading
          description
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query SearchContent($query: String!, $first: Int = 20, $after: String) {
  search(query: $query, first: $first, after: $after) {
    edges {
      node {
        id
        displayName
        changed
        ... on Page {
          heading
          description
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}

query TotalItems {
  Data {
    total
  }
}
